/*
 * spamapi
 *
 * Easily and directly scan and block spam security threats in input.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package Go-CloudmersiveSpamApiClient

// AI advanced spam detection request
type SpamDetectionAdvancedFormSubmissionRequest struct {
	// Form fields and values that you received in your form submission
	InputFormFields []SpamDetectionAdvancedFormField `json:"InputFormFields,omitempty"`
	// True if unsolicited sales should be allowed, false otherwise
	AllowUnsolicitedSales bool `json:"AllowUnsolicitedSales,omitempty"`
	// True if promotional content should be allowed, false otherwise
	AllowPromotionalContent bool `json:"AllowPromotionalContent,omitempty"`
	// True if phishing should be allowed, false otherwise
	AllowPhishing bool `json:"AllowPhishing,omitempty"`
}
