/*
 * spamapi
 *
 * Easily and directly scan and block spam security threats in input.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package Go-CloudmersiveSpamApiClient

// Result of detecting spam using AI
type SpamDetectionAdvancedResponse struct {
	// True if the result is not spam (clean), and false otherwise
	CleanResult bool `json:"CleanResult,omitempty"`
	// True if the input text contains spam, false otherwise
	ContainsSpam bool `json:"ContainsSpam,omitempty"`
	// True if the input text contains unsolicited sales, false otherwise
	ContainsUnsolicitedSales bool `json:"ContainsUnsolicitedSales,omitempty"`
	// True if the input text contains promotional content, false otherwise
	ContainsPromotionalContent bool `json:"ContainsPromotionalContent,omitempty"`
	// True if the input text contains a phishing attempt, false otherwise
	ContainsPhishingAttempt bool `json:"ContainsPhishingAttempt,omitempty"`
}
