/*
 * spamapi
 *
 * Easily and directly scan and block spam security threats in input.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package Go-CloudmersiveSpamApiClient

// Form field submitted to run spam detection on
type SpamDetectionAdvancedFormField struct {
	// Title of the field
	FieldTitle string `json:"FieldTitle,omitempty"`
	// Value of the field
	FieldValue string `json:"FieldValue,omitempty"`
}
