/*
 * spamapi
 *
 * Easily and directly scan and block spam security threats in input.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package Go-CloudmersiveSpamApiClient

// AI advanced spam detection request
type SpamDetectionAdvancedRequest struct {
	// Input text string to detect spam against
	InputString string `json:"InputString,omitempty"`
	// Optional: Specify which AI model to use.  Possible choices are Normal and Advanced.  Default is Advanced.
	Model string `json:"Model,omitempty"`
	// True if unsolicited sales should be allowed, false otherwise
	AllowUnsolicitedSales bool `json:"AllowUnsolicitedSales,omitempty"`
	// True if promotional content should be allowed, false otherwise
	AllowPromotionalContent bool `json:"AllowPromotionalContent,omitempty"`
	// True if phishing should be allowed, false otherwise
	AllowPhishing bool `json:"AllowPhishing,omitempty"`
}
