/*
 * spamapi
 *
 * Easily and directly scan and block spam security threats in input.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package Go-CloudmersiveSpamApiClient

// AI spam detection request
type SpamDetectionRequest struct {
	// Input text string to detect spam against
	InputString string `json:"InputString,omitempty"`
	// Optional: Specify which AI model to use.  Possible choices are Normal and Advanced.  Default is Advanced.
	Model string `json:"Model,omitempty"`
}
